import type { Metadata } from "next";
import { Crimson_Pro } from "next/font/google";
import "./globals.css";

// Import Crimson Pro font
const crimsonPro = Crimson_Pro({
  variable: "--font-crimson-pro",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${crimsonPro.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
